Support rich assertions.
antithesishq/antithesis-sdk-java pull request #21
Opened 2024-10-21 13:26 UTC by wsx-antithesis

2024-10-21 20:18 UTC, herzogp requested changes
Otherwise, looks good.  I don't know about the precision on all possible integral values that can be represented in a double - might result in some inaccuracies.  Nice job handling +/-Infinity.  Is NaN also handled somehow?

2024-10-21 20:18 UTC, herzogp commented on sdk/src/main/java/com/antithesis/sdk/internal/Guidance.java
> +        guidacnNode.put("antithesis_guidance", MAPPER.valueToTree(this));
please repair `guidanceNode` spelling

2024-10-29 14:51 UTC, wsx-antithesis commented
> I don't know about the precision on all possible integral values that can be represented in a double - might result in some inaccuracies.

I followed the Rust SDK behavior (which admittedly can be improved) here. The rational of converting all numeric values to double is that eventually they are serialized & deserialize through JSON, which becomes double in the fuzzer/notebook. The precision issue may result in a few more guidance being reported (when they are rounded to the watermark), but we'll never incorrectly omit one that should have been reported.

> Is NaN also handled somehow?

Good catch! I updated the NaN handling logic so that NaN values are always reported, but they never affect the water mark, so future normal values can still go through. This is the same behavior as the Rust SDK, and I find it sensible.

2024-10-29 14:53 UTC, wsx-antithesis commented on sdk/src/main/java/com/antithesis/sdk/internal/Guidance.java
> +        guidacnNode.put("antithesis_guidance", MAPPER.valueToTree(this));
Thanks, now fixed!

2024-10-29 16:05 UTC, merged